services:
  # MySQL Database
  # TODO: mysql (with volumes), network
  #  mysql:
  #    image: mysql:8.0
  #    container_name:
  #    environment:
  #      MYSQL_ROOT_PASSWORD:
  #      MYSQL_DATABASE:
  #    ports:
  #      - "3306:3306"
  #    volumes:
  #      - mysql_data:/var/lib/mysql
  #      - ./backend/src/main/resources/db/migration:/docker-entrypoint-initdb.d
  #
  #  backend:
  #    build:
  #      context: ./backend
  #      dockerfile:
  #    container_name:
  #    environment:
  #      - SPRING_PROFILES_ACTIVE=prod
  #      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/iksystem?useSSL=false&allowPublicKeyRetrieval=true
  #      - SPRING_DATASOURCE_USERNAME=root
  #      - SPRING_DATASOURCE_PASSWORD=root
  #      - JWT_SECRET=${JWT_SECRET:-defaultSecretKeyChangeInProduction}
  #    ports:
  #      - "8080:8080"
  #    depends_on:
  #      mysql:
  #        condition: service_healthy
  #

  frontend:
    build:
      context: ./frontend
      dockerfile:
    container_name:
    ports:
      - "80:80"
    depends_on:
      - backend

#  mysql_data:
#
