-- Organization
INSERT INTO organization (org_number, legal_name, display_name, contact_email, is_active, created_at, updated_at)
VALUES (937219997, 'Everest Sushi & Fusion AS', 'Everest Sushi', 'kari@everest-sushi.no', 1, NOW(), NOW());

-- Roles
INSERT INTO role (role_name, description, is_system_role) VALUES
('ADMIN', 'Administrator with full access', 1),
('MANAGER', 'Manager with limited admin access', 1),
('KITCHEN_MANAGER', 'Kitchen manager', 1),
('EMPLOYEE', 'Regular employee', 1),
('COOK', 'Cook', 1),
('BARTENDER', 'Bartender', 1),
('WAITER', 'Waiter', 1)
ON DUPLICATE KEY UPDATE role_name = role_name;

-- Users
INSERT INTO app_user (display_name, email, phone, is_active, created_at, updated_at) VALUES
('Tri Tac Le', 'admin@everest-sushi.no', '12345678', 1, NOW(), NOW()),
('Surya', 'surya@personligmai.com', '12345679', 1, NOW(), NOW()),
('Anine Bergen', 'anine@personligmail.com', '12345680', 1, NOW(), NOW()),
('Harald Velde', 'harald@oersonligmail.no', '12345681', 1, NOW(), NOW()),
('Magnus Næssan Gaarder', 'manager@everest-sushi.no', '12345682', 1, NOW(), NOW());

-- Credentials (Password: Test1234!)
-- Hash generated by BCryptPasswordEncoder in the application
INSERT INTO app_user_local_credential (user_id, password_hash, must_change_pw, last_changed_at, failed_attempts, created_at, updated_at)
SELECT user_id,
       '$2a$10$/Z.0lo0byi4feb4kAdcXjOZfC.4mKPQVt.8Xr4LalKlt34X2vHLXm',
       0, NOW(), 0, NOW(), NOW()
FROM app_user;

-- Organization membership
INSERT INTO user_organization (user_id, org_number, is_active, joined_at)
SELECT user_id, 937219997, 1, NOW()
FROM app_user;

-- Role assignments
INSERT INTO user_organization_role (user_id, org_number, role_id, assigned_at, assigned_by_user_id)
SELECT u.user_id, 937219997, r.role_id, NOW(), u.user_id
FROM app_user u
CROSS JOIN role r
WHERE (u.email = 'admin@everest-sushi.no' AND r.role_name = 'ADMIN')
   OR (u.email = 'manager@everest-sushi.no' AND r.role_name = 'KITCHEN_MANAGER')
   OR (u.email = 'anine@personligmail.com' AND r.role_name = 'COOK')
   OR (u.email = 'harald@oersonligmail.no' AND r.role_name = 'BARTENDER')
   OR (u.email = 'surya@personligmai.com' AND r.role_name = 'WAITER');
