classDiagram
    direction LR

    class FrontendApp
    class Router
    class Views
    class ApiClient
    class AuthStore

    class BackendAPI
    class Controllers
    class Services
    class Security
    class Repositories
    class Database

    FrontendApp --> Router
    Router --> Views

    Views --> ApiClient
    Views --> AuthStore

    AuthStore --> ApiClient

    ApiClient --> BackendAPI

    BackendAPI --> Security
    BackendAPI --> Controllers

    Controllers --> Services
    Services --> Repositories
    Repositories --> Database